//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSekronEntities1 : DbContext
    {
        public dbSekronEntities1()
            : base("name=dbSekronEntities1")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_contato> tb_contato { get; set; }
        public virtual DbSet<tb_emedica> tb_emedica { get; set; }
        public virtual DbSet<tb_cartao> tb_cartao { get; set; }
        public virtual DbSet<tb_transacao> tb_transacao { get; set; }
        public virtual DbSet<tb_servico> tb_servico { get; set; }
        public virtual DbSet<tb_mativo> tb_mativo { get; set; }
        public virtual DbSet<tb_tipoocorrencia> tb_tipoocorrencia { get; set; }
        public virtual DbSet<tb_subocorrencia> tb_subocorrencia { get; set; }
        public virtual DbSet<tb_ocorrencia> tb_ocorrencia { get; set; }
        public virtual DbSet<tb_tipoanexo> tb_tipoanexo { get; set; }
        public virtual DbSet<tb_anexo> tb_anexo { get; set; }
        public virtual DbSet<tb_redefinirsenha> tb_redefinirsenha { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
