//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_anexo
    {
        public long codAnexo { get; set; }
        public long codTipoAnexo { get; set; }
        public long codOcorrencia { get; set; }
        public string anexo { get; set; }
        public string tipoAnexo { get; set; }
        public string data { get; set; }
        public string hora { get; set; }
    
        public virtual tb_ocorrencia tb_ocorrencia { get; set; }
        public virtual tb_tipoanexo tb_tipoanexo { get; set; }
    }
}
