//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_emedica
    {
        public long codEmedica { get; set; }
        public long codUsuario { get; set; }
        public string cartaoSus { get; set; }
        public string planoSaude { get; set; }
        public string numeroPlanoSaude { get; set; }
        public string problemaSaude { get; set; }
        public string notasMedicas { get; set; }
        public string alergiasReacoes { get; set; }
        public string medicamentos { get; set; }
        public string tipoSanguineo { get; set; }
        public string peso { get; set; }
        public string altura { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
