//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ocorrencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ocorrencia()
        {
            this.tb_anexo = new HashSet<tb_anexo>();
        }
    
        public long codOcorrencia { get; set; }
        public long codTipoOcorrencia { get; set; }
        public long codUsuario { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string descricaoOcorrencia { get; set; }
        public string data { get; set; }
        public string hora { get; set; }
        public string enderecoOcorrencia { get; set; }
        public string placaVeiculo { get; set; }
    
        public virtual tb_tipoocorrencia tb_tipoocorrencia { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_anexo> tb_anexo { get; set; }
    }
}
