//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_servico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_servico()
        {
            this.tb_transacao = new HashSet<tb_transacao>();
        }
    
        public long codServico { get; set; }
        public long codUsuario { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string data { get; set; }
        public string dataValidade { get; set; }
        public string valor { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_transacao> tb_transacao { get; set; }
    }
}
