//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_subocorrencia
    {
        public long codSubocorrencia { get; set; }
        public long codTipoocorrencia { get; set; }
        public string descricao { get; set; }
    
        public virtual tb_tipoocorrencia tb_tipoocorrencia { get; set; }
    }
}
