//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sekron1.infra
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_usuario()
        {
            this.tb_contato = new HashSet<tb_contato>();
            this.tb_emedica = new HashSet<tb_emedica>();
            this.tb_cartao = new HashSet<tb_cartao>();
            this.tb_servico = new HashSet<tb_servico>();
            this.tb_mativo = new HashSet<tb_mativo>();
            this.tb_ocorrencia = new HashSet<tb_ocorrencia>();
        }
    
        public long codUsuario { get; set; }
        public long codLogin { get; set; }
        public string nome { get; set; }
        public string dataNascimento { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public string celular { get; set; }
        public string telefone { get; set; }
        public string sexo { get; set; }
        public string cep { get; set; }
        public string rua { get; set; }
        public string complemento { get; set; }
        public string numero { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public bool ativo { get; set; }
        public string dataCadastro { get; set; }
        public bool pago { get; set; }
        public string voluntario { get; set; }
        public string fotoPerfil { get; set; }
        public string uidFirebase { get; set; }
        public Nullable<bool> notificacaoAmarela { get; set; }
        public Nullable<bool> notificacaoLaranja { get; set; }
        public Nullable<bool> notificacaoVermelha { get; set; }
        public string enderecoCasa { get; set; }
        public string enderecoTrabalho { get; set; }
        public string carroMarca { get; set; }
        public string carroModelo { get; set; }
        public string carroPlaca { get; set; }
        public string carroFoto { get; set; }
        public string carroCor { get; set; }
        public string cepTrabalho { get; set; }
        public string cepCasa { get; set; }
    
        public virtual tb_login tb_login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_contato> tb_contato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_emedica> tb_emedica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_cartao> tb_cartao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_servico> tb_servico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_mativo> tb_mativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ocorrencia> tb_ocorrencia { get; set; }
    }
}
